### ISSUE TITLE
Method for auto-discovery of cameras on network

### ISSUE THREAD

**Issue by theseankelly** [ifm/ifm3d#194]
Create an API to scan the network and auto-discover all connected O3D/O3X cameras

Some design thoughts:

API should be a static member of the `ifm3d::Camera` class, something like:
```
std::vector<string> ifm3d::Camera::DiscoverDevices()
```
Where the return value is a vector of IP addresses each of which may be used directly with `ifm3d::Camera::MakeShared()`.

Open points on the API:
- not sure there are any useful parameters to expose. Search on specific subnet for example?

Should include a command line utility which prints the IP and type of camera.
```
$ ifm3d discover
Found 3 devices:
  192.168.0.2 (O3D3XX)
  192.168.0.3 (O3X)
  192.168.0.4 (O3D3XX)
```
Open points about the command line tools:
- other information to print on the command line? Device name? Active application?

**Comment by theseankelly** [comment]
FYI we've just open sourced our python implementation here: https://github.com/ifm/python-ipv4-discovery/blob/master/discovery.py

**Comment by theseankelly** [comment]
Updated issue description to include some design notes. @graugans any thoughts?

**Comment by graugans** [comment]
We should consider to use the idea of an ``URI`` instead of the IPv4 address. There might be the case when host names are more useful than raw IP addresses. Related to the additional information. We have the Article number and the MAC address which comes handy. There is also the idea of the vendor and device type which should be used to distinguish the type of the device I would not recommend to use the article number to classify the type of camera (O3X vs. O3D).
