### ISSUE TITLE
How do you find the correct IFM camera on a network of 100s of IFMs? 

### ISSUE THREAD

**Issue by andrew-ampersand** [ifm/ifm3d#286]
I have many IFM O3X100s on the same DHCP server. Each IFM is local to its own Jetson computer. When the Jetson looks for the IFM that is local to it on the network using discovery.py, it usually finds the correct IFM. Sometimes, however it will find the IP address of the wrong IFM (one that is not local to the Jetson). How would you recommend I discover the the correct IFM? It is not guaranteed that the IFM will have the same IP address when it is rebooted.

**Comment by graugans** [comment]
Hey @andrew-ampersand, that is kind of tricky due to the way you have set-up your network. If it is technically possible you could assign a fixed IP for each camera in the DHCP server. Which might sound like a simple solution but will become tricky if you add a new Jetson plus O3X or when switching O3Xs

When working with the discovery.py tool you could check for the [Hostname or the MAC address of the O3X](https://github.com/ifm/python-ipv4-discovery/blob/master/discovery.py#L110). In this case you'll have to maintain a list in your Jetson about the local O3X connected to the Jetson. Again this might be updated when changing the set-up.

I am not sure if this might be solved by using a VLAN for each Jeston / O3X combo and or measuring the ping times of the units. To provide more ideas it would be helpful to have a better understanding of your infrastructure.
